import uuid
from datetime import datetime, timedelta, timezone
from sqlalchemy.orm import Session
from sqlalchemy import text
import logging

from app.services.email_service import send_email

logger = logging.getLogger(__name__)

ALERT_COOLDOWN_MINUTES = 30


# -------------------------------------------------
# INLINE EMAIL TEMPLATE (NO EXTRA FILES)
# -------------------------------------------------

def build_high_risk_email(owner_name: str, scan_text: str):
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; background:#f6f6f6; padding:20px;">
        <div style="max-width:600px; margin:auto; background:#ffffff; padding:20px; border-radius:8px;">
          
          <h2 style="color:#d32f2f;">🚨 High-Risk Security Alert</h2>

          <p>
            A potentially dangerous digital threat was detected for
            <strong>{owner_name}</strong>.
          </p>

          <div style="background:#fff3f3; border-left:4px solid #d32f2f; padding:12px; margin:16px 0;">
            <strong>Detected Content:</strong>
            <p>{scan_text}</p>
          </div>

          <p>
            Please reach out to them immediately and ensure they do not
            share OTPs, passwords, or financial information.
          </p>

          <hr />

          <p style="font-size:12px; color:#777;">
            This alert was generated by GO Suraksha to help protect families
            from digital fraud.
          </p>

        </div>
      </body>
    </html>
    """


# -------------------------------------------------
# CORE FUNCTION (CALLED FROM /analyze)
# -------------------------------------------------

def notify_trusted_contacts(
    db: Session,
    user_id: str,
    scan_id: str,
    alert_type: str = "HIGH_RISK_SCAN",
):
    """
    Create trusted alerts + send email alerts
    ONLY for PAID users and HIGH risk scans.
    """

    # 1️⃣ Cooldown check (anti-spam)
    last_alert_time = db.execute(
        text("""
            SELECT created_at
            FROM trusted_alerts
            WHERE contact_id IN (
                SELECT id
                FROM trusted_contacts
                WHERE owner_user_id = CAST(:uid AS uuid)
            )
            ORDER BY created_at DESC
            LIMIT 1
        """),
        {"uid": user_id},
    ).scalar()

    if last_alert_time:
        # 🔥 FIX: Normalize timezone safely
        if last_alert_time.tzinfo is None:
            last_alert_time = last_alert_time.replace(tzinfo=timezone.utc)

        now = datetime.now(timezone.utc)

        if now - last_alert_time < timedelta(minutes=ALERT_COOLDOWN_MINUTES):
            logger.info("Trusted alert skipped due to cooldown")
            return

    # 2️⃣ Fetch ACTIVE trusted contacts (with email)
    contacts = db.execute(
        text("""
            SELECT id, contact_email
            FROM trusted_contacts
            WHERE owner_user_id = CAST(:uid AS uuid)
              AND status = 'ACTIVE'
              AND contact_email IS NOT NULL
        """),
        {"uid": user_id},
    ).mappings().all()

    if not contacts:
        logger.info("No active trusted contacts with email")
        return

    # 3️⃣ Insert trusted_alerts rows
    for c in contacts:
        db.execute(
            text("""
                INSERT INTO trusted_alerts (
                    id,
                    contact_id,
                    scan_id,
                    alert_type,
                    created_at
                )
                VALUES (
                    :id,
                    :contact_id,
                    :scan_id,
                    :alert_type,
                    now()
                )
            """),
            {
                "id": str(uuid.uuid4()),
                "contact_id": c["id"],
                "scan_id": scan_id,
                "alert_type": alert_type,
            },
        )

    # 4️⃣ Check owner plan + name
    owner = db.execute(
        text("""
            SELECT name, plan
            FROM users
            WHERE id = CAST(:uid AS uuid)
        """),
        {"uid": user_id},
    ).first()

    if not owner or owner.plan != "PAID":
        logger.info("Owner is not PAID — skipping email alerts")
        db.commit()
        return

    owner_name = owner.name or "Your contact"

    # 5️⃣ Fetch scan text (for email content)
    scan = db.execute(
        text("""
            SELECT input_text
            FROM scan_history
            WHERE id = CAST(:sid AS uuid)
        """),
        {"sid": scan_id},
    ).first()

    scan_text = scan.input_text if scan else "A high-risk digital threat was detected."

    # 6️⃣ Send email alerts (FAIL-SAFE)
    for c in contacts:
        try:
            html_body = build_high_risk_email(
                owner_name=owner_name,
                scan_text=scan_text,
            )

            send_email(
                to_email=c["contact_email"],
                subject="🚨 High-Risk Security Alert – GO Suraksha",
                html_body=html_body,
            )

        except Exception as e:
            logger.error(f"Email failed for {c['contact_email']}: {e}")

    db.commit()
