import logging
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.services.alert_logging import log_alert_event
from app.services.notification_service import NotificationService

logger = logging.getLogger(__name__)

ALERT_COOLDOWN_MINUTES = 30
notifier = NotificationService()


def build_high_risk_email(owner_name: str, scan_text: str):
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; background:#f6f6f6; padding:20px;">
        <div style="max-width:600px; margin:auto; background:#ffffff; padding:20px; border-radius:8px;">
          <h2 style="color:#d32f2f;">High-Risk Security Alert</h2>
          <p>
            A potentially dangerous digital threat was detected for
            <strong>{owner_name}</strong>.
          </p>
          <div style="background:#fff3f3; border-left:4px solid #d32f2f; padding:12px; margin:16px 0;">
            <strong>Detected Content:</strong>
            <p>{scan_text}</p>
          </div>
          <p>
            Please reach out to them immediately and ensure they do not
            share OTPs, passwords, or financial information.
          </p>
          <hr />
          <p style="font-size:12px; color:#777;">
            This alert was generated by GO Suraksha to help protect families
            from digital fraud.
          </p>
        </div>
      </body>
    </html>
    """


def notify_trusted_contacts(
    db: Session,
    user_id: str,
    scan_id: str,
    alert_type: str = "HIGH_RISK_SCAN",
    alert_event_id=None,
):
    contacts = db.execute(
        text(
            """
            SELECT id, contact_email, contact_user_id
            FROM trusted_contacts
            WHERE owner_user_id = CAST(:uid AS uuid)
              AND status = 'ACTIVE'
        """
        ),
        {"uid": user_id},
    ).mappings().all()

    if not contacts:
        logger.info("No active trusted contacts with email")
        return {"stored": 0, "delivered": 0}

    stored = 0
    delivered = 0
    for contact in contacts:
        last_alert_time = db.execute(
            text(
                """
                SELECT created_at
                FROM trusted_alerts
                WHERE contact_id = CAST(:contact_id AS uuid)
                ORDER BY created_at DESC
                LIMIT 1
                """
            ),
            {"contact_id": str(contact["id"])},
        ).scalar()
        if last_alert_time:
            if last_alert_time.tzinfo is None:
                last_alert_time = last_alert_time.replace(tzinfo=timezone.utc)
            now = datetime.now(timezone.utc)
            if now - last_alert_time < timedelta(minutes=ALERT_COOLDOWN_MINUTES):
                logger.info("Trusted alert skipped due to cooldown", extra={"contact_id": str(contact["id"])})
                continue

        db.execute(
            text(
                """
                INSERT INTO trusted_alerts (
                    id,
                    contact_id,
                    scan_id,
                    alert_type,
                    created_at
                )
                VALUES (
                    :id,
                    :contact_id,
                    :scan_id,
                    :alert_type,
                    now()
                )
            """
            ),
            {
                "id": str(uuid.uuid4()),
                "contact_id": contact["id"],
                "scan_id": scan_id,
                "alert_type": alert_type,
            },
        )
        stored += 1
        log_alert_event(
            alert_event_id=alert_event_id,
            user_id=user_id,
            trigger_type=alert_type,
            delivery_method="trusted_alerts",
            status="STORED",
        )

    owner = db.execute(
        text(
            """
            SELECT name
            FROM users
            WHERE id = CAST(:uid AS uuid)
        """
        ),
        {"uid": user_id},
    ).first()

    if not owner:
        db.commit()
        return {"stored": stored, "delivered": delivered}

    owner_name = owner.name or "Your contact"

    scan = db.execute(
        text(
            """
            SELECT input_text
            FROM scan_history
            WHERE id = CAST(:sid AS uuid)
        """
        ),
        {"sid": scan_id},
    ).first()

    scan_text = scan.input_text if scan else "A high-risk digital threat was detected."

    for contact in contacts:
        if not contact.get("contact_email"):
            if contact.get("contact_user_id"):
                notifier.send_push_notification(
                    db=db,
                    contact_user_id=contact["contact_user_id"],
                    title=alert_type,
                    body=scan_text,
                    alert_event_id=alert_event_id,
                    user_id=user_id,
                )
            continue
        try:
            html_body = build_high_risk_email(
                owner_name=owner_name,
                scan_text=scan_text,
            )

            notifier.send_email(
                to_email=contact["contact_email"],
                subject="High-Risk Security Alert - GO Suraksha",
                html_body=html_body,
                alert_event_id=alert_event_id,
                user_id=user_id,
            )
            delivered += 1
            if contact.get("contact_user_id"):
                notifier.send_push_notification(
                    db=db,
                    contact_user_id=contact["contact_user_id"],
                    title=alert_type,
                    body=scan_text,
                    alert_event_id=alert_event_id,
                    user_id=user_id,
                )

        except Exception as exc:
            logger.error("Email failed for %s: %s", contact["contact_email"], exc)

    db.commit()
    return {"stored": stored, "delivered": delivered}
