import logging
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.core.features import Feature, has_feature
from app.services.email_service import send_email

logger = logging.getLogger(__name__)

ALERT_COOLDOWN_MINUTES = 30


def build_high_risk_email(owner_name: str, scan_text: str):
    return f"""
    <html>
      <body style="font-family: Arial, sans-serif; background:#f6f6f6; padding:20px;">
        <div style="max-width:600px; margin:auto; background:#ffffff; padding:20px; border-radius:8px;">
          <h2 style="color:#d32f2f;">High-Risk Security Alert</h2>
          <p>
            A potentially dangerous digital threat was detected for
            <strong>{owner_name}</strong>.
          </p>
          <div style="background:#fff3f3; border-left:4px solid #d32f2f; padding:12px; margin:16px 0;">
            <strong>Detected Content:</strong>
            <p>{scan_text}</p>
          </div>
          <p>
            Please reach out to them immediately and ensure they do not
            share OTPs, passwords, or financial information.
          </p>
          <hr />
          <p style="font-size:12px; color:#777;">
            This alert was generated by GO Suraksha to help protect families
            from digital fraud.
          </p>
        </div>
      </body>
    </html>
    """


def notify_trusted_contacts(
    db: Session,
    user_id: str,
    scan_id: str,
    alert_type: str = "HIGH_RISK_SCAN",
):
    last_alert_time = db.execute(
        text(
            """
            SELECT created_at
            FROM trusted_alerts
            WHERE contact_id IN (
                SELECT id
                FROM trusted_contacts
                WHERE owner_user_id = CAST(:uid AS uuid)
            )
            ORDER BY created_at DESC
            LIMIT 1
        """
        ),
        {"uid": user_id},
    ).scalar()

    if last_alert_time:
        if last_alert_time.tzinfo is None:
            last_alert_time = last_alert_time.replace(tzinfo=timezone.utc)

        now = datetime.now(timezone.utc)

        if now - last_alert_time < timedelta(minutes=ALERT_COOLDOWN_MINUTES):
            logger.info("Trusted alert skipped due to cooldown")
            return

    contacts = db.execute(
        text(
            """
            SELECT id, contact_email
            FROM trusted_contacts
            WHERE owner_user_id = CAST(:uid AS uuid)
              AND status = 'ACTIVE'
              AND contact_email IS NOT NULL
        """
        ),
        {"uid": user_id},
    ).mappings().all()

    if not contacts:
        logger.info("No active trusted contacts with email")
        return

    for contact in contacts:
        db.execute(
            text(
                """
                INSERT INTO trusted_alerts (
                    id,
                    contact_id,
                    scan_id,
                    alert_type,
                    created_at
                )
                VALUES (
                    :id,
                    :contact_id,
                    :scan_id,
                    :alert_type,
                    now()
                )
            """
            ),
            {
                "id": str(uuid.uuid4()),
                "contact_id": contact["id"],
                "scan_id": scan_id,
                "alert_type": alert_type,
            },
        )

    owner = db.execute(
        text(
            """
            SELECT name, plan
            FROM users
            WHERE id = CAST(:uid AS uuid)
        """
        ),
        {"uid": user_id},
    ).first()

    if not owner:
        db.commit()
        return

    owner_ctx = type("OwnerCtx", (), {"plan": owner.plan})()
    if not has_feature(owner_ctx, Feature.PRIORITY_SOS):
        logger.info(
            "feature_access_denied user_id=%s plan=%s feature=%s context=trusted_alert_email",
            user_id,
            owner.plan,
            Feature.PRIORITY_SOS.value,
        )
        db.commit()
        return

    owner_name = owner.name or "Your contact"

    scan = db.execute(
        text(
            """
            SELECT input_text
            FROM scan_history
            WHERE id = CAST(:sid AS uuid)
        """
        ),
        {"sid": scan_id},
    ).first()

    scan_text = scan.input_text if scan else "A high-risk digital threat was detected."

    for contact in contacts:
        try:
            html_body = build_high_risk_email(
                owner_name=owner_name,
                scan_text=scan_text,
            )

            send_email(
                to_email=contact["contact_email"],
                subject="High-Risk Security Alert - GO Suraksha",
                html_body=html_body,
            )

        except Exception as exc:
            logger.error("Email failed for %s: %s", contact["contact_email"], exc)

    db.commit()
