from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import text

from app.db import get_db
from app.models.user import User
from app.routes.auth import get_current_user

router = APIRouter(prefix="/family", tags=["Family Dashboard"])


@router.get("/dashboard")
def family_dashboard(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Read-only family security overview.
    Only family head can VIEW members.
    """

    rows = db.execute(
        text("""
            SELECT
                u.id AS user_id,
                u.name,
                u.email,
                u.phone,

                COUNT(sh.id) AS total_scans,
                COUNT(*) FILTER (WHERE sh.risk = 'high') AS high_risk,
                COUNT(*) FILTER (WHERE sh.risk = 'medium') AS medium_risk,
                COUNT(*) FILTER (WHERE sh.risk = 'low') AS low_risk,
                MAX(sh.created_at) AS last_scan_at

            FROM trusted_contacts tc
            JOIN users u
              ON u.id = tc.contact_user_id
            LEFT JOIN scan_history sh
              ON sh.user_id = u.id

            WHERE tc.owner_user_id = CAST(:uid AS uuid)
              AND tc.status = 'ACTIVE'

            GROUP BY u.id, u.name, u.email, u.phone
            ORDER BY last_scan_at DESC NULLS LAST
        """),
        {"uid": str(current_user.id)},
    ).mappings().all()

    members = []

    for r in rows:
        score = 100
        score -= r["high_risk"] * 15
        score -= r["medium_risk"] * 8
        score = max(0, min(100, score))

        members.append({
            "user_id": r["user_id"],
            "name": r["name"],
            "email": r["email"],
            "phone": r["phone"],
            "security_score": score,
            "risk_summary": {
                "high": r["high_risk"],
                "medium": r["medium_risk"],
                "low": r["low_risk"],
            },
            "total_scans": r["total_scans"],
            "last_scan_at": r["last_scan_at"],
        })

    return {
        "family_head": {
            "user_id": str(current_user.id),
            "name": current_user.name,
        },
        "members_count": len(members),
        "members": members,
        "mode": "READ_ONLY",
    }


@router.get("/alerts")
def family_alerts(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    High-risk alerts generated by family members.
    Paid family plans only.
    """

    if current_user.plan not in ("FAMILY_BASIC", "FAMILY_PRO"):
        raise HTTPException(status_code=403, detail="Family plan required")

    rows = db.execute(
        text("""
            SELECT
                fa.created_at,
                u.name AS member_name,
                u.email AS member_email,
                fa.alert_type
            FROM family_alerts fa
            JOIN users u
              ON u.id = fa.member_user_id
            WHERE fa.family_head_user_id = CAST(:uid AS uuid)
            ORDER BY fa.created_at DESC
        """),
        {"uid": str(current_user.id)},
    ).mappings().all()

    return {
        "count": len(rows),
        "alerts": rows,
    }
