ALTER TABLE users
ADD COLUMN IF NOT EXISTS accepted_terms BOOLEAN DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS accepted_terms_at TIMESTAMP NULL;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS terms_version TEXT;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS privacy_version TEXT;
